// <auto-generated />
namespace AbpCompanyName.AbpProjectName.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Ugraded_To_ABP_5_4_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ugraded_To_ABP_5_4_0));
        
        string IMigrationMetadata.Id
        {
            get { return "202003201250482_Ugraded_To_ABP_5_4_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
